#file: noinspection SpellCheckingInspection
run:
  skip-files:
    - ".*_enum\\.go$"
    - "test/*.*"
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: '1.20'
output:
  format: colored-line-number
linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - bodyclose
    - dupl
    - errorlint
    - exportloopref
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - prealloc
    - revive
    - stylecheck
    - whitespace
    - goheader
    - errcheck
    - revive
    - usestdlibvars
    - durationcheck
    - contextcheck
    - decorder
    - gocheckcompilerdirectives
    - grouper
    - musttag
    - prealloc
    - paralleltest
    - unconvert
    - wastedassign
    - wrapcheck
    - nilerr
    - nilnil
linters-settings:
  revive:
    rules:
      - name: datarace
        severity: warning
        disabled: false
  goheader:
    values:
      const:
        AUTHOR: omegarogue
    template: |-
      * Copyright © {{ YEAR }} {{ AUTHOR }}
       * SPDX-License-Identifier: AGPL-3.0-or-later
       *
       * This program is free software: you can redistribute it and/or modify
       * it under the terms of the GNU Affero General Public License as
       * published by the Free Software Foundation, either version 3 of the
       * License, or (at your option) any later version.
       *
       * This program is distributed in the hope that it will be useful,
       * but WITHOUT ANY WARRANTY; without even the implied warranty of
       * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
       * GNU Affero General Public License for more details.
       *
       * You should have received a copy of the GNU Affero General Public License
       * along with this program. If not, see <https://www.gnu.org/licenses/>.
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - style
      - performance
      - opinionated
  govet:
    settings:
      printf:
        funcs:
          - (*github.com/rs/zerolog.Event).Msgf
          - github.com/pkg/errors.Errorf
          - github.com/pkg/errors.Wrapf
          - github.com/pkg/errors.WithMessagef
    enable:
      - structtag
      - unmarshal
      - ifaceassert
issues:
  exclude-rules:
    - linters:
        - stylecheck
      text: "should not use underscores in Go names; func Fuzz(\\w+)_(\\w+) should be Fuzz(\\w+)"
    - linters:
        - goheader
      text: "Code generated by cmd/cgo; DO NOT EDIT."
    - linters:
        - typecheck
      text: "undefined: gdk"
    - linters:
        - typecheck
      text: "undefined: gtk"
    - linters:
        - typecheck
      text: "`v4` redeclared in this block"
    - linters:
        - typecheck
      text: "`v2` redeclared in this block"
    - linters:
        - typecheck
      text: "other declaration of v4"
    - linters:
        - typecheck
      text: "other declaration of v2"
    - linters:
        - typecheck
      text: "undefined: glib"
    - linters:
        - typecheck
      text: "undefined: gio"
    - linters:
        - typecheck
      text: "pattern static/lib.js: no matching files found"
    - path: 'gstreamer/(.+)\.go'
      linters:
        - gocritic
      text: "dupImport"
    - linters:
        - gocritic
      text: "commentedOutCode"