#file: noinspection SpellCheckingInspection
run:
  skip-files:
    - ".*_enum\\.go$"
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: '1.20'
output:
  format: colored-line-number
linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - bodyclose
    - dupl
    - errorlint
    - exportloopref
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - prealloc
    - revive
    - stylecheck
    - whitespace
    - goheader
    - errcheck
    - revive
linters-settings:
  revive:
    rules:
      - name: datarace
        severity: warning
        disabled: false
  goheader:
    values:
      const:
        AUTHOR: omegarogue
    template: |-
      * Copyright © {{ YEAR }} {{ AUTHOR }}
       * SPDX-License-Identifier: AGPL-3.0-or-later
       *
       * This program is free software: you can redistribute it and/or modify
       * it under the terms of the GNU Affero General Public License as
       * published by the Free Software Foundation, either version 3 of the
       * License, or (at your option) any later version.
       * 
       * This program is distributed in the hope that it will be useful,
       * but WITHOUT ANY WARRANTY; without even the implied warranty of
       * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
       * GNU Affero General Public License for more details.
       * 
       * You should have received a copy of the GNU Affero General Public License
       * along with this program.  If not, see <https://www.gnu.org/licenses/>.
  gocritic:
    enabled-tags:
      - opinionated
  govet:
    settings:
      printf:
        funcs:
          - (*github.com/rs/zerolog.Event).Msgf
          - github.com/pkg/errors.Errorf
          - github.com/pkg/errors.Wrapf
          - github.com/pkg/errors.WithMessagef
    enable:
      - structtag
      - unmarshal
      - ifaceassert