#file: noinspection SpellCheckingInspection,SpellCheckingInspection,SpellCheckingInspection,SpellCheckingInspection
name: golangci-lint
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '**/v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
env:
  GO111MODULE: on
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ^1.20.2
          cache: false
      #      - run: sudo apt-get update
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libunwind-dev libgstreamer1.0-dev libgtk-4-dev libsystemd-dev libgstreamer-plugins-base1.0-dev
          version: 0.0.0.3
      - run: go install github.com/abice/go-enum@latest
      - name: Generate
        run: go generate -v ./...
      - run: echo $USER; groups; ls -lha ../../../go/pkg/mod/nhooyr.io/websocket@v1.8.7/dial.go
#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v3
#        with:
#          args: --timeout=60m --verbose --modules-download-mode readonly --issues-exit-code=0
#          only-new-issues: true